name: resonime
description: Aplikasi streaming anime terbaik

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  curved_navigation_bar: ^1.0.3
  cached_network_image: ^3.3.0
  video_player: ^2.8.2
  chewie: ^1.7.0
  http: ^1.1.0
  shimmer: ^2.0.0
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true